# Generated by Django 5.1.1 on 2024-10-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(
                choices=[('available', 'Available'), ('in_use', 'In use')],
                default='available',
                max_length=10,
            ),
        ),
    ]
