# Generated by Django 5.1.1 on 2024-10-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_status_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.CharField(
                choices=[
                    ('available', 'Available'),
                    ('in_use', 'In use'),
                    ('defective', 'Defective'),
                    ('discharged', 'Discharged'),
                ],
                default='available',
                max_length=10,
            ),
        ),
    ]
