# Generated by Django 5.1.1 on 2024-10-27 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_vehicletype_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(
                fields=['start_time'], name='core_trip_start_t_ffc92d_idx'
            ),
        ),
    ]
