# Generated by Django 5.1.1 on 2024-10-24 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_status_vehicle'),
        ('customers', '0002_update_field_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('broke', 'Broke'), ('good', 'Good')],
                        default='good',
                        max_length=10,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                (
                    'location',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='broke_vehicles_location',
                        to='core.location',
                    ),
                ),
                (
                    'vehicle_code',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='broke_vehicle',
                        to='core.vehicle',
                    ),
                ),
            ],
        ),
    ]
