# Generated by Django 5.1.1 on 2024-10-27 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_idx_trip'),
        ('customers', '0004_alter_wallet_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(
                fields=['created_at'], name='customers_p_created_629ec0_idx'
            ),
        ),
    ]
